example/lib/example_web/router.ex
defmodule ExampleWeb.Router do
  use ExampleWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ExampleWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/categories", CategoryController, only: [:index]
    resources "/products", ProductController, only: [:index]
  end
end

example/lib/example/store/category.ex
defmodule Example.Store.Category do
  use Rummage.Ecto.Schema
  import Ecto.Changeset


  schema "categories" do
    field :description, :string
    field :name, :string

    belongs_to :parent_category, __MODULE__

    timestamps()
  end

  @doc false
  def changeset(category, attrs) do
    category
    |> cast(attrs, [:name, :description])
    |> validate_required([:name, :description])
  end
end

example/lib/example_web/controllers/category_controller.ex
defmodule ExampleWeb.CategoryController do
  use ExampleWeb, :controller

  alias Example.Store
  alias Example.Store.Category

  def index(conn, _params) do
    categories = Store.list_categories()
    render(conn, "index.html", categories: categories)
  end
end

example/lib/example_web/views/category_view.ex
defmodule ExampleWeb.CategoryView do
  use ExampleWeb, :view
end

example/lib/example_web/templates/category/index.html.eex
<h2>Listing Categories</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for category <- @categories do %>
    <tr>
      <td><%= category.name %></td>
      <td><%= category.description %></td>

      <td class="text-right">
        <span><%= link "Show", to: category_path(@conn, :show, category), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: category_path(@conn, :edit, category), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: category_path(@conn, :delete, category), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Category", to: category_path(@conn, :new) %></span>