example/lib/example_web/router.ex
defmodule ExampleWeb.Router do
  use ExampleWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ExampleWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/categories", CategoryController, only: [:index]
    resources "/products", ProductController, only: [:index]
  end
end

example/lib/example/store/product.ex
defmodule Example.Store.Product do
  @moduledoc """
  This is Product Ecto.Schema for testing Rummage.Ecto with float values
  and boolean values
  """

  use Rummage.Ecto.Schema, per_page: 3,
    search: Rummage.Ecto.Hook.CustomSearch,
    sort: Rummage.Ecto.Hook.CustomSort,
    paginate: Rummage.Ecto.Hook.CustomPaginate

  import Ecto.Changeset

  @primary_key {:internal_code, :string, autogenerate: false}

  schema "products" do
    field :name, :string
    field :price, :float
    field :availability, :boolean
    field :description, :string

    belongs_to :category, Example.Store.Category

    timestamps()
  end

  @doc false
  def changeset(product, attrs) do
    product
    |> cast(attrs, [:name, :internal_code, :price, :availability, :description])
    |> validate_required([:name, :internal_code, :price, :availability, :description])
  end

  rummage_field :created_at_year do
    {:fragment, "date_part('year', ?)", :inserted_at}
  end

  rummage_field :created_at_month do
    {:fragment, "date_part('month', ?)", :inserted_at}
  end

  rummage_field :created_at_day do
    {:fragment, "date_part('day', ?)", :inserted_at}
  end

  rummage_field :created_at_hour do
    {:fragment, "date_part('hour', ?)", :inserted_at}
  end

  rummage_field :upper_case_name do
    {:fragment, "upper(?)", :name}
  end

  rummage_field :name_or_description do
    {:fragment, "coalesce(?, ?)", :name, :description}
  end

  rummage_scope :category_name_like, [type: :search], fn(term) ->
    {:name, %{assoc: [inner: :category], search_term: term, search_type: :ilike}}
  end

  rummage_scope :parent_category_name_like, [type: :search], fn(term) ->
    {:name, %{assoc: [inner: :category, inner: :parent_category], search_term: term, search_type: :ilike}}
  end

  rummage_scope :category_name, [type: :search], fn(term) ->
    {:name, %{assoc: [inner: :category], search_term: term, search_type: :ilike}}
  end

  rummage_scope :category_name, [type: :sort], fn(order) ->
    %{field: :name, assoc: [inner: :category], order: order, ci: :true}
  end

  rummage_scope :product_index, [type: :paginate], fn(page) ->
    %{per_page: 10, page: page}
  end

  rummage_scope :category_show, [type: :paginate], fn(page) ->
    %{per_page: 5, page: page}
  end

  rummage_scope :category_quarter, [type: :custom_search], fn({query, term}) ->
    query
    |> join(:inner, [q], c in Rummage.Ecto.Category, q.category_id == c.id)
    |> where([..., c], fragment("date_part('quarter', ?)", c.inserted_at) == ^term)
  end

  rummage_scope :category_microseconds, [type: :custom_sort], fn({query, order}) ->
    query
    |> join(:inner, [q], c in Rummage.Ecto.Category, q.category_id == c.id)
    |> order_by([..., c], [{^order, fragment("date_part('microseconds', ?)", c.inserted_at)}])
  end

  rummage_scope :small_page, [type: :custom_paginate], fn({query, page}) ->
    offset = 5 * (page - 1)

    query
    |> limit(5)
    |> offset(^offset)
  end
end

example/lib/example_web/controllers/product_controller.ex
defmodule ExampleWeb.ProductController do
  use ExampleWeb, :controller
  use Rummage.Phoenix.Controller, rummage_schema: Example.Store.Product

  alias Example.Store
  alias Example.Store.Product

  @compatible_css ~w(
    bootstrap3
    bootstrap4
    materialize
    foundation
    semantic
  )

  action_fallback ExampleWeb.FallbackController

  def index(conn, params) do
    css = Map.get(params, "css", "bootstrap3")

    case Enum.member?(@compatible_css, css) do
      true -> apply(__MODULE__, :"products_#{css}", [conn, params])
      _ ->
        conn
        |> put_flash(:error, "CSS requested isn't valid: #{css}")
        |> redirect(to: "/")
        |> halt()
    end
  end

  def products_bootstrap3(conn, params) do
    rummage = rummage_params(params["rummage"])

    {products, rummage} = Store.list_products(rummage)
    categories = Store.list_categories()

    render(conn, "bootstrap3.html",
           products: products,
           categories: categories,
           rummage: rummage)
  end

  def products_bootstrap4(conn, params) do
    rummage = rummage_params(params["rummage"])

    {products, rummage} = Store.list_products(rummage)
    categories = Store.list_categories()

    render(conn, "bootstrap4.html",
           products: products,
           categories: categories,
           rummage: rummage)
  end

  def products_materialize(conn, params) do
    rummage = rummage_params(params["rummage"])

    {products, rummage} = Store.list_products(rummage)
    categories = Store.list_categories()

    render(conn, "materialize.html",
           products: products,
           categories: categories,
           rummage: rummage)
  end

  def products_foundation(conn, params) do
    rummage = rummage_params(params["rummage"])

    {products, rummage} = Store.list_products(rummage)
    categories = Store.list_categories()

    render(conn, "foundation.html",
           products: products,
           categories: categories,
           rummage: rummage)
  end

  def products_semantic(conn, params) do
    rummage = rummage_params(params["rummage"])

    {products, rummage} = Store.list_products(rummage)
    categories = Store.list_categories()

    render(conn, "semantic.html",
           products: products,
           categories: categories,
           rummage: rummage)
  end
end

example/lib/example_web/views/product_view.ex
defmodule ExampleWeb.ProductView do
  use ExampleWeb, :view
  use Rummage.Phoenix.View

end

example/lib/example_web/templates/product/bootstrap3.html.eex
<head>
  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>

<%
  name = @rummage
    |> Map.get(:search, %{})
    |> Map.get(:name, %{})

  name_assoc = Map.get(name, :assoc, [])

  {name_search_term, category_name_search_term} =
    case name_assoc do
      [] -> {Map.get(name, :search_term), ""}
      [{:inner, :category}] -> {"", Map.get(name, :search_term)}
      %{inner: :category} -> {"", Map.get(name, :search_term)}
    end

  internal_code = @rummage
    |> Map.get(:search, %{})
    |> Map.get(:internal_code, %{})
    |> Map.get(:search_term, "")
%>

<div class="container" style="background-color: lightgrey">
  <h3>Bootstrap 3</h3>
  <form class="form" action="<%= product_path(@conn, :index) %>" method="get">
    <div class="form-group">
      <input type="hidden" class="form-control" name="css" value="bootstrap3">
    </div>

    <div class="form-group">
      <input type="text" class="form-control" name="rummage[search][category_name]" placeholder="Search By Category Name" value="<%= category_name_search_term %>">
    </div>
    <button type="submit" class="btn btn-default">
      <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
    </button>
  </form>

  </br>
  <form class="form" action="<%= product_path(@conn, :index) %>" method="get">
    <div class="form-group">
      <input type="hidden" class="form-control" name="css" value="bootstrap3">
    </div>

    <div class="form-group">
      <input type="text" class="form-control" name="rummage[search][name][search_term]" placeholder="Search By Name" value="<%= name_search_term %>">
      <input type="hidden" class="form-control" name="rummage[search][name][search_expr]" value="where">
      <input type="hidden" class="form-control" name="rummage[search][name][search_type]" value="ilike">
    </div>
    <div class="form-group">
      <input type="text" class="form-control" name="rummage[search][internal_code][search_term]" placeholder="Search By Internal Code" value="<%= internal_code %>">
      <input type="hidden" class="form-control" name="rummage[search][internal_code][search_expr]" value="where">
      <input type="hidden" class="form-control" name="rummage[search][internal_code][search_type]" value="ilike">
    </div>

    <button type="submit" class="btn btn-default">
      <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
    </button>
  </form>

  </br>
</div>

</br>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name <%= sort_link(%{field: :name}, @conn.request_path, @rummage, slugs: %{css: "bootstrap3"}) %></th>
      <th>Price <%= sort_link(%{field: :price}, @conn.request_path, @rummage, slugs: %{css: "bootstrap3"}) %></th>
      <th>Internal Code <%= sort_link(%{field: :internal_code}, @conn.request_path, @rummage, slugs: %{css: "bootstrap3"}) %></th>
      <th>Availability <%= sort_link(%{field: :availability}, @conn.request_path, @rummage, slugs: %{css: "bootstrap3"}) %></th>
      <th>Category Name <%= sort_link(%{scope: :category_name, type: :sort, schema: Example.Store.Product}, @conn.request_path, @rummage, slugs: %{css: "bootstrap3"}) %></th>
    </tr>
  </thead>
  <tbody>
<%= for product <- @products do %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= product.internal_code %></td>
      <td><%= product.availability %></td>
      <td><%= Enum.find(@categories, & product.category_id == &1.id).name %></td>
    </tr>
<% end %>
  </tbody>
</table>

<%= pagination_links(@conn.request_path, @rummage, slugs: %{css: "bootstrap3"},
                     max_pagination_links: 3) %>

example/lib/example_web/templates/product/bootstrap4.html.eex
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />
</head>

<%
  name = @rummage
    |> Map.get(:search, %{})
    |> Map.get(:name, %{})

  name_assoc = Map.get(name, :assoc, [])

  {name_search_term, category_name_search_term} =
    case name_assoc do
      [] -> {Map.get(name, :search_term), ""}
      [{:inner, :category}] -> {"", Map.get(name, :search_term)}
      %{inner: :category} -> {"", Map.get(name, :search_term)}
    end

  internal_code = @rummage
    |> Map.get(:search, %{})
    |> Map.get(:internal_code, %{})
    |> Map.get(:search_term, "")
%>

<div class="container" style="background-color: lightgrey">
  </br>
  <h3>Bootstrap 4</h3>
  <form class="form" action="<%= product_path(@conn, :index) %>" method="get">
    <div class="form-group">
      <input type="hidden" class="form-control" name="css" value="bootstrap4">
    </div>

    <div class="form-group">
      <input type="text" class="form-control" name="rummage[search][category_name]" placeholder="Search By Category Name" value="<%= category_name_search_term %>">
    </div>
    <button type="submit" class="btn btn-default">
      <span class="oi oi-magnifying-glass"></span>
    </button>
  </form>

  </br>
  <form class="form" action="<%= product_path(@conn, :index) %>" method="get">
    <div class="form-group">
      <input type="hidden" class="form-control" name="css" value="bootstrap4">
    </div>

    <div class="form-group">
      <input type="text" class="form-control" name="rummage[search][name][search_term]" placeholder="Search By Name" value="<%= name_search_term %>">
      <input type="hidden" class="form-control" name="rummage[search][name][search_expr]" value="where">
      <input type="hidden" class="form-control" name="rummage[search][name][search_type]" value="ilike">
    </div>
    <div class="form-group">
      <input type="text" class="form-control" name="rummage[search][internal_code][search_term]" placeholder="Search By Internal Code" value="<%= internal_code %>">
      <input type="hidden" class="form-control" name="rummage[search][internal_code][search_expr]" value="where">
      <input type="hidden" class="form-control" name="rummage[search][internal_code][search_type]" value="ilike">
    </div>

    <button type="submit" class="btn btn-default">
      <span class="oi oi-magnifying-glass"></span>
    </button>
  </form>

  </br>
</div>

</br>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name <%= sort_link(%{field: :name}, @conn.request_path, @rummage, slugs: %{css: "bootstrap4"}, css: Rummage.Phoenix.Bootstrap4) %></th>
      <th>Price <%= sort_link(%{field: :price}, @conn.request_path, @rummage, slugs: %{css: "bootstrap4"}, css: Rummage.Phoenix.Bootstrap4) %></th>
      <th>Internal Code <%= sort_link(%{field: :internal_code}, @conn.request_path, @rummage, slugs: %{css: "bootstrap4"}, css: Rummage.Phoenix.Bootstrap4) %></th>
      <th>Availability <%= sort_link(%{field: :availability}, @conn.request_path, @rummage, slugs: %{css: "bootstrap4"}, css: Rummage.Phoenix.Bootstrap4) %></th>
      <th>Category Name <%= sort_link(%{scope: :category_name, type: :sort, schema: Example.Store.Product}, @conn.request_path, @rummage, slugs: %{css: "bootstrap4"}, css: Rummage.Phoenix.Bootstrap4) %></th>
    </tr>
  </thead>
  <tbody>
<%= for product <- @products do %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= product.internal_code %></td>
      <td><%= product.availability %></td>
      <td><%= Enum.find(@categories, & product.category_id == &1.id).name %></td>
    </tr>
<% end %>
  </tbody>
</table>

<%= pagination_links(@conn.request_path, @rummage, slugs: %{css: "bootstrap4"},
                     max_pagination_links: 3, css: Rummage.Phoenix.Bootstrap4) %>

example/lib/example_web/templates/product/foundation.html.eex
<head>
  <link rel = "stylesheet" href = "https://cdnjs.cloudflare.com/ajax/libs/foundation/6.0.1/css/foundation.css">
  <script src = "https://cdnjs.cloudflare.com/ajax/libs/foundation/6.0.1/js/foundation.min.js"></script>
  <script src = "https://cdnjs.cloudflare.com/ajax/libs/foundation/6.0.1/js/vendor/jquery.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">
</head>

<%
  name = @rummage
    |> Map.get(:search, %{})
    |> Map.get(:name, %{})

  name_assoc = Map.get(name, :assoc, [])

  {name_search_term, category_name_search_term} =
    case name_assoc do
      [] -> {Map.get(name, :search_term), ""}
      [{:inner, :category}] -> {"", Map.get(name, :search_term)}
      %{inner: :category} -> {"", Map.get(name, :search_term)}
    end

  internal_code = @rummage
    |> Map.get(:search, %{})
    |> Map.get(:internal_code, %{})
    |> Map.get(:search_term, "")
%>

<div style="background-color: lightgrey">
  <h3>Foundation</h3>

  <form class="form" action="<%= product_path(@conn, :index) %>" method="get">
    <input type="hidden" class="form-control" name="css" value="foundation">

    <label>Search By Category Name </label>
    <input type="text" class="form-control" name="rummage[search][category_name]" placeholder="Search By Category Name" value="<%= category_name_search_term %>">
    <button type="submit" class="btn btn-default">
      <i class="fi-page-search"></i>
    </button>
  </form>

  </br>
  <form class="form" action="<%= product_path(@conn, :index) %>" method="get">
    <input type="hidden" class="form-control" name="css" value="foundation">

    <label>Search By Name </label>
    <input type="text" class="form-control" name="rummage[search][name][search_term]" placeholder="Search By Name" value="<%= name_search_term %>">
    <input type="hidden" class="form-control" name="rummage[search][name][search_expr]" value="where">
    <input type="hidden" class="form-control" name="rummage[search][name][search_type]" value="ilike">

    <label>Search By Internal Code </label>
    <input type="text" class="form-control" name="rummage[search][internal_code][search_term]" placeholder="Search By Internal Code" value="<%= internal_code %>">
    <input type="hidden" class="form-control" name="rummage[search][internal_code][search_expr]" value="where">
    <input type="hidden" class="form-control" name="rummage[search][internal_code][search_type]" value="ilike">

    <button type="submit" class="btn btn-default">
      <i class="fi-page-search"></i>
    </button>
  </form>

  </br>
</div>

</br>


<table class="hover table-border" style="border: 1px solid #e6e6e6;">
  <thead>
    <tr>
      <th>Name <%= sort_link(%{field: :name}, @conn.request_path, @rummage, slugs: %{css: "foundation"}, css: Rummage.Phoenix.Foundation) %></th>
      <th>Price <%= sort_link(%{field: :price}, @conn.request_path, @rummage, slugs: %{css: "foundation"}, css: Rummage.Phoenix.Foundation) %></th>
      <th>Internal Code <%= sort_link(%{field: :internal_code}, @conn.request_path, @rummage, slugs: %{css: "foundation"}, css: Rummage.Phoenix.Foundation) %></th>
      <th>Availability <%= sort_link(%{field: :availability}, @conn.request_path, @rummage, slugs: %{css: "foundation"}, css: Rummage.Phoenix.Foundation) %></th>
      <th>Category Name <%= sort_link(%{scope: :category_name, type: :sort, schema: Example.Store.Product}, @conn.request_path, @rummage, slugs: %{css: "foundation"}, css: Rummage.Phoenix.Foundation) %></th>
    </tr>
  </thead>
  <tbody>
<%= for product <- @products do %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= product.internal_code %></td>
      <td><%= product.availability %></td>
      <td><%= Enum.find(@categories, & product.category_id == &1.id).name %></td>
    </tr>
<% end %>
  </tbody>
</table>

<%= pagination_links(@conn.request_path, @rummage, slugs: %{css: "foundation"},
                     max_pagination_links: 3, css: Rummage.Phoenix.Foundation) %>

example/lib/example_web/templates/product/materialize.html.eex
<head>
  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<%
  name = @rummage
    |> Map.get(:search, %{})
    |> Map.get(:name, %{})

  name_assoc = Map.get(name, :assoc, [])

  {name_search_term, category_name_search_term} =
    case name_assoc do
      [] -> {Map.get(name, :search_term), ""}
      [{:inner, :category}] -> {"", Map.get(name, :search_term)}
      %{inner: :category} -> {"", Map.get(name, :search_term)}
    end

  internal_code = @rummage
    |> Map.get(:search, %{})
    |> Map.get(:internal_code, %{})
    |> Map.get(:search_term, "")
%>

<div style="background-color: lightgrey">
  <h3>Materialize</h3>

  <form class="form" action="<%= product_path(@conn, :index) %>" method="get">
    <input type="hidden" class="form-control" name="css" value="materialize">

    <label>Search By Category Name </label>
    <input type="text" class="form-control" name="rummage[search][category_name]" placeholder="Search By Category Name" value="<%= category_name_search_term %>">
    <button type="submit" class="btn btn-default">
      <i class="material-icons">sync</i>
    </button>
  </form>

  </br>
  <form class="form" action="<%= product_path(@conn, :index) %>" method="get">
    <input type="hidden" class="form-control" name="css" value="materialize">

    <label>Search By Name </label>
    <input type="text" class="form-control" name="rummage[search][name][search_term]" placeholder="Search By Name" value="<%= name_search_term %>">
    <input type="hidden" class="form-control" name="rummage[search][name][search_expr]" value="where">
    <input type="hidden" class="form-control" name="rummage[search][name][search_type]" value="ilike">

    <label>Search By Internal Code </label>
    <input type="text" class="form-control" name="rummage[search][internal_code][search_term]" placeholder="Search By Internal Code" value="<%= internal_code %>">
    <input type="hidden" class="form-control" name="rummage[search][internal_code][search_expr]" value="where">
    <input type="hidden" class="form-control" name="rummage[search][internal_code][search_type]" value="ilike">

    <button type="submit" class="btn btn-default">
      <i class="material-icons">sync</i>
    </button>
  </form>

  </br>
</div>

</br>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name <%= sort_link(%{field: :name}, @conn.request_path, @rummage, slugs: %{css: "materialize"}, css: Rummage.Phoenix.Materialize) %></th>
      <th>Price <%= sort_link(%{field: :price}, @conn.request_path, @rummage, slugs: %{css: "materialize"}, css: Rummage.Phoenix.Materialize) %></th>
      <th>Internal Code <%= sort_link(%{field: :internal_code}, @conn.request_path, @rummage, slugs: %{css: "materialize"}, css: Rummage.Phoenix.Materialize) %></th>
      <th>Availability <%= sort_link(%{field: :availability}, @conn.request_path, @rummage, slugs: %{css: "materialize"}, css: Rummage.Phoenix.Materialize) %></th>
      <th>Category Name <%= sort_link(%{scope: :category_name, type: :sort, schema: Example.Store.Product}, @conn.request_path, @rummage, slugs: %{css: "materialize"}, css: Rummage.Phoenix.Materialize) %></th>
    </tr>
  </thead>
  <tbody>
<%= for product <- @products do %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= product.internal_code %></td>
      <td><%= product.availability %></td>
      <td><%= Enum.find(@categories, & product.category_id == &1.id).name %></td>
    </tr>
<% end %>
  </tbody>
</table>

<%= pagination_links(@conn.request_path, @rummage, slugs: %{css: "materialize"},
                     max_pagination_links: 3, css: Rummage.Phoenix.Materialize) %>

example/lib/example_web/templates/product/semantic.html.eex
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.9/semantic.min.css"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.js"></script>
</head>

<%
  name = @rummage
    |> Map.get(:search, %{})
    |> Map.get(:name, %{})

  name_assoc = Map.get(name, :assoc, [])

  {name_search_term, category_name_search_term} =
    case name_assoc do
      [] -> {Map.get(name, :search_term), ""}
      [{:inner, :category}] -> {"", Map.get(name, :search_term)}
      %{inner: :category} -> {"", Map.get(name, :search_term)}
    end

  internal_code = @rummage
    |> Map.get(:search, %{})
    |> Map.get(:internal_code, %{})
    |> Map.get(:search_term, "")
%>

<div style="background-color: lightgrey">
  <h3>Semantic</h3>
  <form class="form" action="<%= product_path(@conn, :index) %>" method="get">
    <input type="hidden" class="form-control" name="css" value="semantic">

    <label>Search By Category Name </label>
    <input type="text" class="form-control" name="rummage[search][category_name]" placeholder="Search By Category Name" value="<%= category_name_search_term %>">

    <button type="submit" class="btn btn-default">
      <i class="search icon"></i>
    </button>
  </form>

  </br>
  <form class="form" action="<%= product_path(@conn, :index) %>" method="get">
    <input type="hidden" class="form-control" name="css" value="semantic">

    <label>Search By Name </label>
    <input type="text" class="form-control" name="rummage[search][name][search_term]" placeholder="Search By Name" value="<%= name_search_term %>">
    <input type="hidden" class="form-control" name="rummage[search][name][search_expr]" value="where">
    <input type="hidden" class="form-control" name="rummage[search][name][search_type]" value="ilike">

    <label>Search By Internal Code </label>
    <input type="text" class="form-control" name="rummage[search][internal_code][search_term]" placeholder="Search By Internal Code" value="<%= internal_code %>">
    <input type="hidden" class="form-control" name="rummage[search][internal_code][search_expr]" value="where">
    <input type="hidden" class="form-control" name="rummage[search][internal_code][search_type]" value="ilike">

    <button type="submit" class="btn btn-default">
      <i class="search icon"></i>
    </button>
  </form>

  </br>
</div>

</br>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Name <%= sort_link(%{field: :name}, @conn.request_path, @rummage, slugs: %{css: "semantic"}, css: Rummage.Phoenix.Semantic) %></th>
      <th>Price <%= sort_link(%{field: :price}, @conn.request_path, @rummage, slugs: %{css: "semantic"}, css: Rummage.Phoenix.Semantic) %></th>
      <th>Internal Code <%= sort_link(%{field: :internal_code}, @conn.request_path, @rummage, slugs: %{css: "semantic"}, css: Rummage.Phoenix.Semantic) %></th>
      <th>Availability <%= sort_link(%{field: :availability}, @conn.request_path, @rummage, slugs: %{css: "semantic"}, css: Rummage.Phoenix.Semantic) %></th>
      <th>Category Name <%= sort_link(%{scope: :category_name, type: :sort, schema: Example.Store.Product}, @conn.request_path, @rummage, slugs: %{css: "semantic"}, css: Rummage.Phoenix.Semantic) %></th>
    </tr>
  </thead>
  <tbody>
<%= for product <- @products do %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= product.internal_code %></td>
      <td><%= product.availability %></td>
      <td><%= Enum.find(@categories, & product.category_id == &1.id).name %></td>
    </tr>
<% end %>
  </tbody>
</table>

<%= pagination_links(@conn.request_path, @rummage, slugs: %{css: "semantic"},
                     max_pagination_links: 3, css: Rummage.Phoenix.Semantic) %>